services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist/user-management-system
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0 